language: ruby
rvm:
  - 1.9.3
addons:
  apt:
    packages:
    - graphviz
script: ./tutorial/build.sh
after_success: ./tutorial/update-gh-pages.sh
env:
  global:
    secure: molF4N6WO21tOQWsq2Wpj810UKJwqYf+IgltNjwLDJ6GG42o0w1Ae4mNc6NQ4FPngF7Tl4x8LqJbo9rRjdS1ZblAz7ARP4Y2s41ClKA3q4jNMS2/1yKKCX/4YqKsbwi+pOZ66/908MDqih1khB0nvJtA9RHeSbVFs1q1OyonWEUmUasP4PXR9U9y8UV+KVFIP/+NcOsCNEoHfVSNqAp1RAOobPsHd72CJ6eq06XhlcB/BpBYgIQ6UQm1cU1sB74PNida82TjJqN0uebOvb/gqCPM01Br1PDktgHa2Sznc1VlcMhicLkj9gL/MPiudwkpwtsrzaV8nnq6ewAZoKPsqtNYZ7CdsnogbUKf4owMjRWx6muGSt9+rKMW6LzZutBetCAWMnTTaxbni6FjwC2cnpkgyDohcBVl60Ei8oCXUHIq+F2K+mQASSy2skz8sV17qBx5sqmHFmCVvVBmlstmVnDXBSVbX8kTDq+WHlTOHlm2eZscHNKLZqkjsyweHCWd7v0t3rwXqN8YgWXq/PJp8kbkqYE12UXOyEHDn9m0EzLUGk/QQf/zZJERzj8/e0TZffWLoZSs2iHJH1qJE/0lHEU+/udAQvc5BbEEQCuEnKuRQY+9FOaja0cO1rKf2nPdzA9UC65FZQwIO8mBLiN0i9mIs+bIbSZpAc3DUw0t66Y=
